#!/usr/bin/env bash
#
# Universal installer for Desktop File Maker
# Works on all Linux distributions (Arch, Ubuntu, Fedora, Debian, etc.)
# No root required - installs to ~/.local
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/venv"
BIN_DIR="$HOME/.local/bin"

# Print functions
print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_header() {
    echo ""
    echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  Desktop File Maker - Universal Installer${NC}"
    echo -e "${BLUE}════════════════════════════════════════════════════════${NC}"
    echo ""
}

# Check if Python 3 is available
check_python() {
    print_info "Checking Python installation..."
    
    if ! command -v python3 &> /dev/null; then
        print_error "Python 3 is not installed"
        echo ""
        echo "Please install Python 3.8 or higher:"
        echo "  Arch:   sudo pacman -S python"
        echo "  Ubuntu: sudo apt install python3 python3-venv"
        echo "  Fedora: sudo dnf install python3"
        exit 1
    fi
    
    PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
    print_success "Found Python $PYTHON_VERSION"
}

# Create virtual environment
create_venv() {
    print_info "Setting up virtual environment..."
    
    if [ -d "$VENV_DIR" ]; then
        print_warning "Virtual environment already exists, recreating..."
        rm -rf "$VENV_DIR"
    fi
    
    python3 -m venv "$VENV_DIR"
    print_success "Virtual environment created"
}

# Install dependencies
install_dependencies() {
    print_info "Installing dependencies..."
    
    # Activate venv
    source "$VENV_DIR/bin/activate"
    
    # Upgrade pip
    pip install --quiet --upgrade pip setuptools wheel
    
    # Install the package in editable mode
    pip install --quiet -e "$SCRIPT_DIR"
    
    print_success "Dependencies installed"
}

# Create launcher script
create_launcher() {
    print_info "Creating launcher script..."
    
    # Ensure ~/.local/bin exists
    mkdir -p "$BIN_DIR"
    
    # Create launcher script
    LAUNCHER="$BIN_DIR/desktop-file-maker"
    
    cat > "$LAUNCHER" << 'EOF'
#!/usr/bin/env bash
# Desktop File Maker launcher
# Auto-generated by install.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")/projects/desktop-file-maker"

# Try to find installation directory
if [ ! -d "$INSTALL_DIR" ]; then
    # Fallback: search common locations
    for DIR in \
        "$HOME/projects/desktop-file-maker" \
        "$HOME/Desktop/desktop-file-maker" \
        "$HOME/desktop-file-maker" \
        "$HOME/.local/share/desktop-file-maker"; do
        if [ -d "$DIR" ]; then
            INSTALL_DIR="$DIR"
            break
        fi
    done
fi

if [ ! -d "$INSTALL_DIR" ]; then
    echo "Error: Cannot find Desktop File Maker installation"
    echo "Please reinstall or run from the installation directory"
    exit 1
fi

VENV_DIR="$INSTALL_DIR/venv"

if [ ! -d "$VENV_DIR" ]; then
    echo "Error: Virtual environment not found at $VENV_DIR"
    echo "Please run install.sh again"
    exit 1
fi

# Activate venv and run
source "$VENV_DIR/bin/activate"
python3 -m src.main "$@"
EOF

    # Update the launcher to use the actual installation directory
    sed -i "s|INSTALL_DIR=\".*\"|INSTALL_DIR=\"$SCRIPT_DIR\"|" "$LAUNCHER"
    
    chmod +x "$LAUNCHER"
    print_success "Launcher created at $LAUNCHER"
}

# Create desktop entry for easy launching
create_desktop_entry() {
    print_info "Creating desktop entry for easy access..."
    
    DESKTOP_DIR="$HOME/.local/share/applications"
    DESKTOP_FILE="$DESKTOP_DIR/desktop-file-maker.desktop"
    
    # Ensure applications directory exists
    mkdir -p "$DESKTOP_DIR"
    
    # Create desktop entry
    cat > "$DESKTOP_FILE" << EOF
[Desktop Entry]
Type=Application
Name=Desktop File Maker
Comment=Create and manage .desktop files with a modern TUI
Exec=$LAUNCHER
Icon=application-x-desktop
Categories=Development;Utility;
Terminal=true
StartupNotify=false
Keywords=desktop;file;creator;appimage;
EOF
    
    chmod +x "$DESKTOP_FILE"
    print_success "Desktop entry created at $DESKTOP_FILE"
}

# Main installation
main() {
    print_header
    
    check_python
    create_venv
    install_dependencies
    create_launcher
    create_desktop_entry
    
    echo ""
    print_success "Installation complete!"
    echo ""
    echo "No system modifications required! You can run Desktop File Maker in these ways:"
    echo ""
    echo "  1. From the application menu (search for 'Desktop File Maker')"
    echo ""
    echo "  2. Run the launcher directly:"
    echo -e "     ${GREEN}$BIN_DIR/desktop-file-maker${NC}"
    echo ""
    echo "  3. From the installation directory:"
    echo -e "     ${GREEN}make run${NC}"
    echo ""
    echo "  4. Or create an alias for convenience:"
    echo -e "     ${GREEN}alias dfm='$BIN_DIR/desktop-file-maker'${NC}"
    echo ""
    print_info "Note: The application will appear in your application menu for easy access!"
}

# Run installation
main
